language: python
python: "2.7"
sudo: required
cache:
  pip: true
  directories:
    - $HOME/buildout-cache
env:
  matrix:
    - PLONE_VERSION=4.3.x BUILDOUT=buildout
    - PLONE_VERSION=5.0.x BUILDOUT=buildout
    - PLONE_VERSION=5.1.x BUILDOUT=buildout
    - PLONE_VERSION=5.2.x BUILDOUT=buildout
    # - PLONE_VERSION=4.3.x BUILDOUT=staging
    # - PLONE_VERSION=5.0.x BUILDOUT=staging
    # - PLONE_VERSION=5.1.x BUILDOUT=staging
    # - PLONE_VERSION=4.3.x BUILDOUT=live
    # - PLONE_VERSION=5.0.x BUILDOUT=live
    # - PLONE_VERSION=5.1.x BUILDOUT=live
before_install:
  - mkdir -p $HOME/buildout-cache/{eggs,downloads}
  - mkdir $HOME/.buildout
  - echo "[buildout]" > $HOME/.buildout/default.cfg
  - echo "download-cache = $HOME/buildout-cache/downloads" >> $HOME/.buildout/default.cfg
  - echo "eggs-directory = $HOME/buildout-cache/eggs" >> $HOME/.buildout/default.cfg
install:
  - pip install -r requirements.txt
script:
  - sed -ie "s#plone-x.x.x.cfg#plone-$PLONE_VERSION.cfg#" buildout.cfg
  - buildout -c $BUILDOUT.cfg
